name: Launch High-Performance VM and Display Server URL

on:
  workflow_dispatch:

jobs:
  launch-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install megatools, VirtualBox, and ngrok
        run: |
          sudo apt-get update
          sudo apt-get install -y megatools virtualbox
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar xvzf ngrok-v3-stable-linux-amd64.tgz
          sudo mv ngrok /usr/local/bin

      - name: Download file from Mega
        env:
          MEGA_LINK: "https://mega.nz/file/poRUkJDQ#vqfe7NwG54c3PvhvSmMYSoo567OUB34xJgIC2_N08VY"
        run: |
          megadl --path=./downloaded_file.ova "$MEGA_LINK"

      - name: Import OVA and configure VM
        run: |
          VM_NAME="HighPerformanceVM"
          OVA_FILE="downloaded_file.ova"
          VBoxManage import $OVA_FILE --vsys 0 --vmname $VM_NAME
          
          # Disable USB controller
          VBoxManage modifyvm $VM_NAME --usbehci off
          VBoxManage modifyvm $VM_NAME --usbxhci off
          
          # Optimize VM settings for performance
          VBoxManage modifyvm $VM_NAME --cpus 4
          VBoxManage modifyvm $VM_NAME --memory 8192
          VBoxManage modifyvm $VM_NAME --vram 128
          VBoxManage modifyvm $VM_NAME --accelerate3d on
          VBoxManage modifyvm $VM_NAME --ioapic on
          VBoxManage modifyvm $VM_NAME --hwvirtex on
          VBoxManage modifyvm $VM_NAME --nestedpaging on
          VBoxManage modifyvm $VM_NAME --largepages on
          
          # Start the VM
          VBoxManage startvm $VM_NAME --type headless

      - name: Start ngrok tunnel
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ngrok authtoken $NGROK_AUTH_TOKEN
          ngrok http 81 --log=stdout > ngrok.log &
          sleep 10
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Server URL: $NGROK_URL"

      - name: Keep the workflow running
        run: |
          echo "High-performance VM is running. Server URL: $NGROK_URL"
          while true; do
            sleep 300
            VBoxManage list runningvms | grep "$VM_NAME" > /dev/null 2>&1 || exit 1
          done